- hosts: target1
  become: yes
  tasks: 

    - name: Install Epel
      yum: 
        name: epel-release
        state: latest

    - name: Install nginx
      yum:
        name: nginx 
        state: latest

    - name: start nginx
      template: 
        src: index.html
        dest: /usr/share/nginx/html/index.html
      
    - name: restart nginx
      service:
        name: nginx
        dest: started
