- hosts: localhost
  become: true
  tasks: 

    - name: Install Epel repo
      yum: 
        name: epel-release
        state: present

    - name: Install nginx
      yum:
        name: nginx 
        state: present

    - name: insert index page
      template: 
        src: index.html
        dest: /usr/share/nginx/html/index.html
      
    - name: restart nginx
      service:
        name: nginx
        dest: started
